<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backend.Orleans.GrainClasses\Backend.Orleans.GrainClasses.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
      <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Server" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Streaming.AzureStorage" Version="9.2.1" />
      <PackageReference Include="OrleansDashboard" Version="8.2.0" />
    </ItemGroup>

</Project>
