<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backend.Orleans.SharedContracts\Backend.Orleans.SharedContracts.csproj" />
      <ProjectReference Include="..\Backend.SignalR.SharedContracts\Backend.SignalR.SharedContracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Orleans.Runtime" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Sdk" Version="9.2.1" />
      <PackageReference Include="Microsoft.Orleans.Streaming" Version="9.2.1" />
    </ItemGroup>

</Project>
